name: customer_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  timeline_tile: ^2.0.0
  flutter_secure_storage: ^9.2.4
  firebase_core: ^3.10.1
  firebase_cloud_firestore: ^5.4.4
  firebase_messaging: ^15.2.1
  firebase_auth: ^5.4.1
  flutter_local_notifications: ^18.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  file_picker: ^8.3.5
  google_maps_flutter: ^2.10.0
  google_places_flutter: ^2.0.9
  firebase_database: ^11.3.2
  intl: ^0.19.0
  geolocator: ^13.0.2
  google_maps_webservice: ^0.0.20-nullsafety.5
  shared_preferences: ^2.5.2
  flutter_launcher_icons: ^0.14.3
  jwt_decoder: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Eina03
      fonts:
        - asset: assets/fonts/muli/Eina03.ttf
  assets:
    - assets/prepairing.gif  
    - assets/Slim Container with Water.png
    - assets/Round Container with Water.png
    - assets/Water Bottle.png
    - assets/default.png
    - assets/banner.png
    - assets/logo.jpg
    - assets/icon.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"